# Generated by Django 2.2.16 on 2022-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/noname.jpj', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
