# Generated by Django 2.2.16 on 2022-05-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220514_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
